name: 'AI enabled PR review action'
description: 'This Github action will incercept the PR diff and provide AI generated feedbacks as comments'
inputs:
  github-access-token:
    description: 'This token will be use to authenicate Github APIs'
    required: false
    default: ${{ github.token }}
  openai-key:
    description: 'The OpenAI API key'
    required: true
  prompt:
    description: 'Pormpt will use to tell AI model what feedbacks needed for privided code'
    required: false
    default: Please review the code, provide your feedbacks. Please assume that code is in Javascript and you are following es2015 standards for code reivew.
  post-if-error:
    description: 'Whether to post a comment if there was an error'
    required: false
    default: 'true'
  model-name:
    description: 'Open AI generative AI model name'
    required: false
    default: 'gpt-3.5-turbo'

outputs:
  results:
    description: 'PR Review result'
    value: ${{ steps.pr-review.outputs.reviewresult }}

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run OpenAI code review
      id: pr-review
      run: |
        git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | python ${{ github.action_path }}/main.py > result.txt
        echo 'reviewresult<<EOF' >> $GITHUB_OUTPUT
        echo "$(cat result.txt)" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai-key }}
        GITHUB_TOKEN: ${{ inputs.github-access-token }}
        MODEL: ${{ inputs.model-name }}
        PROMPT: ${{ inputs.prompt }}
        COMMIT_TITLE: ${{ github.event.pull_request.title }}
        COMMIT_BODY: ${{ github.event.pull_request.body }}

    - name: Show error result
      id: err-output
      if: failure()
      run: |
        echo 'errorresult<<EOF' >> $GITHUB_OUTPUT
        echo "ERROR: $(cat result.txt)" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
        echo "Review result and error: $(cat result.txt)"
      shell: bash

    - name: Create comment
      if: success() || (inputs.post-if-error && inputs.post-if-error != 'false')
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ steps.pr-review.outputs.reviewresult && steps.pr-review.outputs.reviewresult || steps.err-output.outputs.errorresult }}
        reactions: '+2'
