name: ai-enabled-pr-review
authir: Suneet Bansal
description: This will be a github action which would review PR changes and push comments
inputs:
  github-token:
    description: Github token for authentication
    required: false
    default: ${{github.token}}
  open-ai-token:
    description: Token of Open AI account
    required: true
    default: OpenAIToken
  model-name:
    description: Generative AI model name
    required: false
    default: gpt-3.5-turbo
  prompt:
    descrption: You can provide the prompt what kind of analysis you required from Generatibe AI model
    required: false
    default: |
      Please review the code and share your feedbacks.
  max-length:
    description: 'Maximum number of characters to submit to OpenAI'
    required: false
    default: 4000
outputs:
  results:
    description: 'The results of the code review'
    value: ${{ steps.pr-review.outputs.openaireviewresult }}
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        
    - name: Prepare python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run python
      run: python ${{ github.action_path }}/main.py
      shell: bash
      
    - name: Install python dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
      
    - name: Print PR diff
      id: pr-review
      run: git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | python ${{ github.action_path }}/main.py > output.txt
           echo 'openaireviewresult<<EOF' >> $GITHUB_OUTPUT
           echo "$(cat output.txt)" >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OPENAI_API_KEY: ${{ inputs.open-ai-token }}
        COMMIT_TITLE: ${{ github.event.pull_request.title }}
        COMMIT_BODY: ${{ github.event.pull_request.body }}
        MODEL_NAME: ${{ inputs.model-name }}
        PROMPT: ${{ inputs.prompt }}
        MAX_LENGTH: ${{ inputs.max-length }}
        
    - name: Show output in case of failure
      id: err-output
      if: failure()
      run: |
        echo 'errorresult<<EOF' >> $GITHUB_OUTPUT
        echo "ERROR: $(cat output.txt)" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
        echo "Review result and error: $(cat output.txt)"
      shell: bash
      
    - name: Push comment
      if: success() || (inputs.post-if-error && inputs.post-if-error != 'false')
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ steps.pr-review.outputs.openaireviewresult && steps.pr-review.outputs.openaireviewresult || steps.err-output.outputs.errorresult }}
        reactions: '+1'
      


