name: ai-enabled-pr-review
authir: Suneet Bansal
description: This will be a github action which would review PR changes and push comments
inputs:
  github-token:
    description: Github token for authentication
    required: false
    default: ${{github.token}}
  open-ai-token:
    description: Token of Open AI account
    required: true
    default: OpenAIToken
  model-name:
    description: Generative AI model name
    required: false
    default: gpt-3.5-turbo
  prompt:
    descrption: You can provide the prompt what kind of analysis you required from Generatibe AI model
    required: false
    default: |
      Please review the code and share your feedbacks.
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Prepare python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run python
      run: python ${{ github.action_path }}/main.py
      shell: bash
    - name: Print PR diff
      run: git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | python ${{ github.action_path }}/main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      


